 
 use MinhaApiCore

 --select NEWID()

 SELECT * FROM FORNECEDORES

 SELECT * FROM ENDERECOS

 SELECT * FROM PRODUTOS

 SELECT * FROM ASPNETUSERS
 --UPDATE ASPNETUSERS SET LOCKOUTEND = NULL, ACCESSFAILEDCOUNT = 0
 